version: "3"

# docker run --privileged -dit --name kacpp-mail --net kaawsnet -p 25:25 -p 465:465 -p 587:587 -v /home:/home/mail_users -v /home/local_etc:/usr/local/etc kagalpandh/kacpp-mail

services:
    kacpp-samba:
        image: kagalpandh/kacpp-samba
        container_name: kacpp-samba
        volumes:
            - /home/local_etc:/usr/local/etc
            - /home/data/backup:/home/backup
            - /home/doc:/home/doc
            - /home/img:/home/image
            - /home/music:/home/music
            - /home/movie:/home/movie
            - /home/storage:/home/storage
            - /home/karaspadmin:/home/samba_users/karaspadmin
            - /home/karaspdev:/home/samba_users/karaspdev
              #            - /home/timemachine:/home/timemachine
              #            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        network_mode: host
        expose:
            - "137"
            - "138"
            - "139"
            - "445"
            - "5357"
            - "5358"
            - "3702"
#         networks:
#             - raspinet
#         ports:
#             - "137:137/udp"
#             - "138:138/udp"
#             - "139:139/tcp"
#             - "445:445/tcp"
#             - "5357:5357/tcp"
#             - "5358:5358/tcp"
#             - "3702:3702/tcp"
#             - "3702:3702/udp"
        cap_add:
            - SYS_ADMIN
        privileged: true
#         restart: always
        env_file: kacpp-samba.src
#         entrypoint: /bin/bash
#         environment:
#             PGDATA: /home/data/db/pgdata
# networks:
#     raspinet:
#         external: true


