version: "3"

# docker run --privileged -dit --name kacpp-mail --net kaawsnet -p 25:25 -p 465:465 -p 587:587 -v /home:/home/mail_users -v /home/local_etc:/usr/local/etc kagalpandh/kacpp-mail

services:
    kacpp-mail:
        image: kagalpandh/kacpp-samba
        container_name: kacpp-samba
        volumes:
            - /home/local_etc:/usr/local/etc
            - /home/backup:/home/backup
            - /home/doc:/home/doc
            - /home/img:/home/image
            - /home/movie:/home/movie
            - /home/karaspadmin:/home/samba_users/karaspadmin
            - /home/karaspdev:/home/samba_users/karaspdev
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            - raspinet
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        cap_add:
            - SYS_ADMIN
        privileged: true
        restart: always
        env_file: kacpp-samba.src
#         environment:
#             PGDATA: /home/data/db/pgdata
networks:
    raspinet:
        external: true


